### PR TITLE
Set localo for dnf5 run.

### PR DESCRIPTION
**Pull request by j-mracek**
It is required to provide translated texts

Closes: https://github.com/rpm-software-management/dnf5/issues/1375

### CODE REVIEW

**Comment by ppisar** [comment]
Could you correct a typo in "Set localo for dnf5 run." commit message and remove the trailing full stop?

**Comment by kontura** [comment]
The `dnf5-5.2.0.0` branch has been merged into `main`, please target only `main` again.

**Comment by jrohel** [comment]
@j-mracek  Looks OK. But please correct the typo and rebase to the "main" branch as mentioned in previous comments.

**Comment by j-mracek** [comment]
I have created new PR for main branch therefore I am closing the PR in favor of https://github.com/rpm-software-management/dnf5/pull/1408

**Pull request closed without merging**
