### PR TITLE
swig: Fix comps iterator wrappers

### LINKED ISSUE #296: TypeError: 'EnvironmentQuery' object is not iterable
Some queries like `EnvironmentQuery` and `GroupQuery` doesn't seem to be iterable. However, you can iterate over `RepoQuery`.

```
base = libdnf5.base.Base()
base.setup()
query = libdnf5.comps.EnvironmentQuery(base)
```

If I try to iterate the items of the query I get a `TypeError` exception.

```
>>> print([env.get_environmentid() for env in query])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'EnvironmentQuery' object is not iterable
```

If I try to iterate the output of `query.list()` I get a similar exception.

```
>>> print([env.get_environmentid() for env in query.list()])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'SwigPyObject' object is not iterable
```

### PR DESCRIPTION
**Pull request by jan-kolarik**
`EnvironmentQuery` and `GroupQuery` iterators and related wrappers fixed.

Closes #296.

### CODE REVIEW

**Comment by kontura** [comment]
Some Python unittests for this would be nice.
If you prefer we can leave that for later by keeping the issue open for example.

**Comment by jan-kolarik** [comment]
@kontura Yep definitely... I have my internal TODO item to cover more API tests including this soon... I can create an issue for that if it's OK :slightly_smiling_face:

**Comment by jan-kolarik** [comment]
Hmm... But let's add some to this one as it's not yet merged...

**Comment by kontura** [comment]
Thanks!

**Pull request merged**
