### PR TITLE
Rename libdnf => libdnf5

### PR DESCRIPTION
**Pull request by evan-goode**
Rename `libdnf` namespace and include paths to `libdnf5`. See https://github.com/rpm-software-management/dnf5/issues/608.

### CODE REVIEW

**Comment by evan-goode** [comment]
@jhorel @jan-kolarik hi, since y'all are more familiar with SWIG, would either of you be able to take a look at the two Python tests that I commented out in 40d6200? It's `test_query` and `test_transaction` in `test/python3/libdnf5/tutorial/test_tutorial.py`. All the tests are passing except these two, and I can't figure out what's wrong. I'm seeing the following error and I'm not sure how to investigate it.

```
terminate called after throwing an instance of 'Swig::DirectorMethodException'
  what():  SWIG director method error. Error detected when calling 'DownloadCallbacks.mirror_failure'
```

I know the error is going to be straightforward, some occurrence of `libdnf` that I didn't replace with `libdnf5`, but I can't find it. Any help would be really appreciated!

**Comment by jan-kolarik** [comment]
> @jhorel @jan-kolarik hi, since y'all are more familiar with SWIG, would either of you be able to take a look at the two Python tests that I commented out in [40d6200](https://github.com/rpm-software-management/dnf5/commit/40d6200262a5def5d75e1883357c85d578edc959)? It's `test_query` and `test_transaction` in `test/python3/libdnf5/tutorial/test_tutorial.py`. All the tests are passing except these two, and I can't figure out what's wrong. I'm seeing the following error and I'm not sure how to investigate it.
> 
> ```
> terminate called after throwing an instance of 'Swig::DirectorMethodException'
>   what():  SWIG director method error. Error detected when calling 'DownloadCallbacks.mirror_failure'
> ```
> 
> I know the error is going to be straightforward, some occurrence of `libdnf` that I didn't replace with `libdnf5`, but I can't find it. Any help would be really appreciated!

Sure, I will take a look ...

**Comment by evan-goode** [comment]
> I was looking into that and it doesn't seem to be connected with this PR as it currently throws the same error for me using current `main`

Oh fantastic, thanks for looking into it, and thanks to @pkratoch for the patch. I thought I had ruled that out since I couldn't reproduce it on the `main` branch, but if there was an isolation issue with the tests then that makes sense. It just passed for me after `rm -rf ~/.cache/libdnf5`.

I dropped the commit that commented out the tests and rebased onto main. This should be RFR now.

**Comment by evan-goode** [comment]
Notes for reviewers:

- You can find occurrences of `libdnf` without the trailing `5` with `git grep -r -e libdnf --and --not -e libdnf5`
- Focus on occurrences of "libdnf5" in strings: You can use the following to find occurrences of "libdnf5" inside single or double quotes, skipping the #include and %include lines: `git grep -r \( -e '".*libdnf5.*"' -e "'.*libdnf5.*'" \) --and --not -e '^ *[%#]include'`
- Also focus on CMakeLists.txt

**Comment by evan-goode** [comment]
Rebased on top of the 'module enable' changes that were merged.

**Review by jrohel — APPROVED** [review]

**Comment by jrohel** [comment]
I did a review. It looks good. And I agree with merge to unblock others PR.

**Comment by kontura** [comment]
I have rebased this because I broke the PR by merging something else.
We can merge once the CI finishes.

**Comment by m-blaha** [comment]
Thank you guys!

**Pull request merged**
