### PR TITLE
Fix repository specific excludes

### PR DESCRIPTION
**Pull request by m-blaha**
rq.filter_id(disable_excludes, libdnf::sack::QueryCmp::NOT_GLOB) in case of empty `disable_excludes` filters out all repositories.

Resolves https://github.com/rpm-software-management/dnf5/issues/233

### CODE REVIEW

**Comment by m-blaha** [comment]
There is also another way how to fix it.

What is the desired behavior of `bool match_string(const std::string & value, QueryCmp cmp, const std::vector<std::string> & patterns)` function in case the `patterns` vector is empty and the `cmp` comparator is negative? - e.g. `rq.filter_id([], libdnf::sack::QueryCmp::NOT_GLOB)` in this issue, which leads to `match_string(repo_id, libdnf::sack::QueryCmp::NOT_GLOB, [])`

I believe it should return `true`. Any comments?

https://github.com/rpm-software-management/dnf5/blob/1329442c4c2c58d046823e7a83ce7cf45fd25e92/libdnf/common/sack/match_string.cpp#L88-L97

**Comment by kontura** [comment]
> I believe it should return `true`. Any comments?

It would also make sense to me. It seems like a cleaner solution, especially since we have tests for this. 
If we modify `match_string()` I would also change `match_int64()` in the same way.

**Comment by m-blaha** [comment]
I tried to fix the behavior of `match_string()` function in case one (or both) of operands are vectors and the `cmp` operator is negative. I tried to describe the new behavior both in commit message and in the comments.
The fix for `match_int64()` is still not present, but I'd appreciate a partial review here - to make sure that the logic change makes sense.

**Comment by kontura** [comment]
The PR looks good, but I think that in the commit msg: `match_string("fedora", NOT_GLOB, ["fedora", "testing"]) would return true` is wrong. "fedora" is in the string list and since we use `NOT_GLOB` it would return false no?

**Comment by m-blaha** [comment]
I should have written the commit message more clearly. The part you mentioned is an example of clearly wrong behaviour of current (unfixed by this pach) implementation. Let me try to re-formulate the commit message.

**Comment by kontura** [comment]
I see, thanks, it is much more understandable for me now.

**Pull request merged**
