### PR TITLE
dnf5: Add "mc" alias for "makecache"

### LINKED ISSUE #811: Implement `mc` alias for makecache
Aliases are defined in https://github.com/rpm-software-management/dnf5/blob/main/dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf.

### PR DESCRIPTION
**Pull request by hellozee**
Fixes #811

### CODE REVIEW

**Comment by hellozee** [comment]
Something is off with the CI 😓

**Comment by inknos** [comment]
I would drop the clang fix commit for now. The whole `static`/`inline` situation is being reworked here https://github.com/rpm-software-management/dnf5/issues/1072. I invite you to take part in the discussion though :)

I also rerun the ci to check what was the problem. waiting for it to finish

**Comment by hellozee** [comment]
Sorry had to force push, messed up my commit history

**Comment by inknos** [comment]
> Sorry had to force push, messed up my commit history

no problem :) also feel free to add yourself to the authors

https://github.com/rpm-software-management/dnf5/blob/main/AUTHORS.md

regarding tests.
createrepo_c failing tests are addressed in a separate pr
dnf tests fail for some reason that's unclear to me at the moment

so lgtm. I would merge it after you add your author commit

**Pull request merged**
