### PR TITLE
repoquery: set conflicts/requires between arguments

### PR DESCRIPTION
**Pull request by kontura**
For: https://github.com/rpm-software-management/dnf5/issues/122
Also move the `--qf` alias into the formatting group.

### CODE REVIEW

**Review by jan-kolarik — APPROVED** [review]
LGTM

**Comment by kontura** [comment]
Rebased due to conflicts.

**Comment by j-mracek** [comment]
LGTM, feel free to merge it when all tests pass

**Comment by kontura** [comment]
There is one failing test that is unrelated - it is fixed [here](https://github.com/rpm-software-management/createrepo_c/pull/375).

**Pull request merged**
