### PR TITLE
Update toml11-devel usage for 4.0.0

### PR DESCRIPTION
**Pull request by kontura**
This should fix the rawhide build.

### CODE REVIEW

**Comment by kontura** [comment]
I believe the failed `Pre Commit` formatting is wrong, I prefer the current format.

**Comment by evan-goode** [comment]
Thanks. I will wait for this before releasing DNF 5.2.6.0.

> I believe the failed `Pre Commit` formatting is wrong, I prefer the current format.

Maybe the current format is better, but I think it's still better just to keep the formatter happy.

**Comment by kontura** [comment]
To make the `f41` and `rawhide` builds work we need: https://src.fedoraproject.org/rpms/toml11/pull-request/5 and https://src.fedoraproject.org/rpms/toml11/pull-request/4.

Since the builds on those versions are failing anyway I guess we don't need to block this PR on that.

**Comment by jan-kolarik** [comment]
> To make the `f41` and `rawhide` builds work we need: https://src.fedoraproject.org/rpms/toml11/pull-request/5 and https://src.fedoraproject.org/rpms/toml11/pull-request/4.
> 
> Since the builds on those versions are failing anyway I guess we don't need to block this PR on that.

Thanks for taking care of it!

**Pull request merged**
