### PR TITLE
doc: Use PGP instead of GPG

### PR DESCRIPTION
**Pull request by ppisar**
The public-key technology is called Pretty Good Privacy. GPG is a synonymous for GnuPG, a piece of software which DNF5 does not use.

### CODE REVIEW

**Comment by pmatilai** [comment]
Erm. PGP is the name of a proprietary implementation, just like GnuPG is the name of one open-source implementation.
OpenPGP is the name *technology*.

**Comment by ppisar** [comment]
OpenPGP is a name invented for the purpose of IETF standardization coming years after creation of PGP. See <https://www.ietf.org/rfc/rfc1991.html>. It's like insisting on calling ODF "Open Document Format for Office Applications".

**Comment by pmatilai** [comment]
Sure the OpenPGP name was invented later. 
It doesn't change the fact that PGP is the name of the  *proprietary program*, still sold even. I wouldn't want us to be associated with THAT.

**Comment by pmatilai** [comment]
Besides, PGP is a trademard: https://trademarks.justia.com/744/67/pgp-74467812.html

That's one of the reasons people changed their PGP references to GPG back in the day. It wasn't much better, but at least GnuPG folks wouldn't come sue you.

You really don't want to go to using PGP, that's nothing but asking for trouble. There's a proper name for the standard, we should use it.

**Pull request merged**
