### PR TITLE
dnfdaemon: Catch timeout during CheckAuthorization

### PR DESCRIPTION
**Pull request by m-blaha**
- set a timeout for the user to enter the password (default 25 seconds
  seems to be too short)
- catch timeout error - otherwise the error is returned to the client
  causing the original call to fail with timeout

For example:

The user invokes the do_transaction() method on the Goal interface. The
first action of the do_transaction handler is to verify that the user is
authorized to run an RPM transaction. If an authentication agent is
available, this may result in prompting the user to enter their
password. If the user ignores the prompt, after a timeout period, the
result should be a "Not authorized" error.

However, without this patch, the result would be a "Method call timed
out," which is misleading. While the user called do_transaction(), the
timeout did not occur at this stage.

For: https://github.com/rpm-software-management/dnf5/issues/1187

### CODE REVIEW

**Comment by ppisar** [comment]
The code looks reasonable. Though I'd like to see documented the hard-coded 2-minute timeout in dnf5daemon_server(8) or dnf5daemon-dbus-api(8).

Also I'd like to try the patch, but I don't know how to configure polkit to ask a user for a password. Now it immediately rejects a non-superuser.

**Comment by ppisar** [comment]
Put it short, please amend dnf5daemon_server(8) with a notice about the 2-minute timeout and I will approve this pull request.

**Comment by anaselli** [comment]
Just a question, have you experienced that after a timeout the transaction would fail if the user gives the right password? Because I'm almost sure it worked for me, but the call returned "Method call timed out,", IIUC now it fails with "Not authorized", but if the transaction worked, that does not have a real sense to me...

**Comment by anaselli** [comment]
> Just a question, have you experienced that after a timeout the transaction would fail if the user gives the right password? Because I'm almost sure it worked for me, but the call returned "Method call timed out,", IIUC now it fails with "Not authorized", but if the transaction worked, that does not have a real sense to me...

I just tested, waited a lot given the right password and the package had not installed, that means that probably it is not the same issue as reported in  issue #1187, I would like to test my issue with this patch to be sure, but since it is in mageia i need @Conan-Kudo help...

**Comment by ppisar** [comment]
> have you experienced that after a timeout the transaction

I was unable to get polkit to ask for a password. Maybe in requires some fancy graphical application I don't have installed. I always got immediate rejection.

**Comment by m-blaha** [comment]
Although I think this fix is correct, it apparently does not resolve the original issue. I need to re-investigate.

**Comment by m-blaha** [comment]
@ppisar I've added a commit with the documentation improvement.

**Review by ppisar — APPROVED** [review]
Good.

**Comment by anaselli** [comment]
> Although I think this fix is correct, it apparently does not resolve the original issue. I need to re-investigate.

agreed

**Pull request merged**
