### PR TITLE
Make most descriptions for `dnf5 --help` translatable.

### PR DESCRIPTION
**Pull request by bc-lee**
Use `_(msgId)` in `bgettext-lib.h` to mark text as eligible for
translation. This will allow translators to translate the short
descriptions of the commands in `dnf5 --help`. Further changes will be
required to make each command description translatable.

Related: #1736

### CODE REVIEW

**Comment by ppisar** [comment]
The patch looks good. It seems you tried to mark all short description which are visible in `dnf5 --help` output. However, some commands are still missing. E.g.:

builddep
changelog
clean

Lee, are going to correct your current pull request? Or should I simply merge it as it is and fix the missing descriptions later?

**Comment by bc-lee** [comment]
> Lee, are going to correct your current pull request? Or should I simply merge it as it is and fix the missing descriptions later?

I prefer an incremental approach since it would take much longer if we wanted to finish all of the texts related to localization in this PR, and I don't think these changes are necessarily dependent on other PRs.

**Comment by ppisar** [comment]
Then please change the commit title. E.g. replace "each command"  with "most of the commands".

**Comment by bc-lee** [comment]
> Then please change the commit title. E.g. replace "each command" with "most of the commands".

Done. Could reviewers please check the title and the commit message?

**Comment by ppisar** [comment]
You have changed a title of this pull request. I meant changing a title of the git commit message. That's what counts because it will be forever in the git log. Please update the git commit.

**Comment by bc-lee** [comment]
> You have changed a title of this pull request. I meant changing a title of the git commit message. That's what counts because it will be forever in the git log. Please update the git commit.

Before applying the changes to the commit messages, I intentionally updated the title and description of this PR. This is because: 1) Many GitHub-based projects amend multiple commits in a PR, so each commit message is not as important as the PR title and description, and 2) Changing commit messages requires a force push, which isn't recommended for all projects, and I'm not sure if this project (`dnf5`) allows it.

Nonetheless, I have updated the commit messages as well. Please take a look.

**Pull request merged**
