### PR TITLE
Advisory: obsoletes and noarch <-> arch upgrades

### PR DESCRIPTION
**Pull request by kontura**
Related bz to noarch <-> arch upgrades:
https://bugzilla.redhat.com/show_bug.cgi?id=2124483

Marking as `blocked` until it is resolved in dnf4.

### CODE REVIEW

**Comment by j-mracek** [comment]
LGTM - Is there anything why we should not merge it (test enablement, ...)?

**Comment by kontura** [comment]
> LGTM - Is there anything why we should not merge it (test enablement, ...)?

I have created a PR with additional enabled tests that go together with this: https://github.com/rpm-software-management/ci-dnf-stack/pull/1162

I have also rebased this PR and fixed a JIRA link in the comment that was wrong.

I think we can merge now.

**Comment by j-mracek** [comment]
Perfect, I see that the last test is still in progress. @kontura May I ask you to merge the PR when it pass?

**Review by j-mracek — APPROVED** [review]

**Comment by kontura** [comment]
@j-mracek I had to add one more commit to fix an issue this PR had.
Namely it continued to use an advisory even after it was resolved which meant that `upgrade --security` could upgrade packages that had an old already resolved advisory. We do have a CI test for this that failed.

I have resolved this by using a new `AdvisoryPackage` method `is_resolved_in(libdnf::rpm::PackageSet pkgs)` alternatively the functionality could be moved to `PackageSet` or `PackageQuery` and it would take an `AdvisoryPackage`, but to me it seems a better fit like this.

**Comment by j-mracek** [comment]
LGTM

**Pull request merged**
