### PR TITLE
swig: Fix TransactionItemReason wrappers

### LINKED ISSUE #216: Python Bindings: Memory leak in `Package.get_reason()`
In this gist (https://gist.github.com/gotmax23/9786917434121c55165e512bf8e7f37d), there are two Python scripts that query for `yt-dlp` and print the `reason` attr. One uses dnf and the other uses libdnf5. 

dnf returns either a string or None. libdnf5 returns a SwigPyObject that doesn't allow accessing the value and results in a memory leak. I guess libdnf5 should return None here because it doesn't have access to dnf's history db.

``` console
$ ./reason.py
yt-dlp-2022.11.11-1.fc37.noarch
<class 'str'>
weak-dependency
```

``` console
$ ./reason5.py
yt-dlp-2022.11.11-1.fc37.noarch
<class 'SwigPyObject'>
<Swig Object of type 'libdnf::transaction::TransactionItemReason *' at 0x7fe0c5964270>
swig/python detected a memory leak of type 'libdnf::transaction::TransactionItemReason *', no destructor found
```

### PR DESCRIPTION
**Pull request by jan-kolarik**
Include transaction module prior to dependent modules, otherwise enum wrappers are not ready for these modules.

Resolves #216.

### CODE REVIEW

**Comment by jan-kolarik** [comment]
I will also add the CI API test for this.

**Comment by gotmax23** [comment]
This seems to fix the problem. I now get

``` console
$ ./reason.py
yt-dlp-2022.11.11-1.fc37.noarch
<class 'str'>
weak-dependency
$ ./reason5.py
yt-dlp-2022.11.11-1.fc37.noarch
<class 'int'>
4
$ python -c 'from libdnf5.transaction import TransactionItemReason_WEAK_DEPENDENCY; print(TransactionItemReason_WEAK_DEPENDENCY)'
4
```

**Comment by gotmax23** [comment]
In the tests, would it make sense to also assert that `package.get_reason()` equals `libdnf5.transaction.TransactionItemReason_NONE`?

**Comment by jan-kolarik** [comment]
> In the tests, would it make sense to also assert that `package.get_reason()` equals `libdnf5.transaction.TransactionItemReason_NONE`?

Actually it's much better than comparing the value to `0` as the enum definition could change in the future. Thanks for the suggestion, I'll change it immediately.

**Comment by jrohel** [comment]
OK

**Pull request merged**
