### PR TITLE
dnf5: Statistics: total and downloaded pkgs size, installed and freed space

### PR DESCRIPTION
**Pull request by jrohel**
Solves issue https://github.com/rpm-software-management/dnf5/issues/342

### CODE REVIEW

**Comment by jrohel** [comment]
The code is ready, but we need to agree on the output format. Below are examples of the old DNF output and my suggestion of how the new output might look. However, we need to discuss the actual form of the new output.

----
`dnf swap iftop atop`  (the package "atop" needs to be downloaded)
**Old DNF:**
```
Total download size: 199 k
```
Mising information about used space.

**DNF5:**
``` 
Total size of incoming pakages is 199 KiB. Need to download 199 KiB.
After unpacking 375 KiB will be used (installed 473 KiB, removed 98 KiB).
```
----
`dnf swap iftop atop`  (the package "atop" is cached)
**Old DNF:**
```
Total size: 199 k
```
Mising information about used space.

**DNF5:**
``` 
Total size of incoming pakages is 199 KiB. Need to download 0 B.
After unpacking 375 KiB will be used (installed 473 KiB, removed 98 KiB).
```
----
`dnf remove iftop` 
**Old DNF:**
```
Freed space: 98 k
```
**DNF5:**
``` 
Total size of incoming pakages is 0 B. Need to download 0 B.
After unpacking 98 KiB will be freed (installed 0 B, removed 98 KiB).
```
----
`dnf install atop htop`  (the package "atop" is cached)
**Old DNF:**
```
Total size: 384 k
Total download size: 185 k
Installed size: 914 k
```
**DNF5:**
``` 
Total size of incoming pakages is 384 KiB. Need to download 185 KiB.
After unpacking 914 KiB will be used (installed 914 KiB, removed 0 B).
```

**Comment by jan-kolarik** [comment]
For me, it seems OK in most cases. But for the `remove` command I suppose the format could be different and less verbose as there will never be any incoming package, right? Btw typo `pakages` => `packages`.

**Comment by jrohel** [comment]
@jan-kolarik Thanks. I thinking about these changes:
- fix typo `packet` => `packets`
- `(installed 914 KiB, removed 0 B)` => `(install 914 KiB, remove 0 B)`
- Show `Total size of incoming packages is...` line only if there are incoming packages.

**Comment by jan-kolarik** [comment]
I am also wondering about the line for the `remove` command: "After **unpacking** 98 KiB will be freed". Maybe change the phrase to something more general like "After the operation xxx B of space will be used/freed"...

**Comment by m-blaha** [comment]
FWIW, on the API we use inbound/outbound terminology.
Ubuntu uses this wording:

Need to get 13.0 kB of archives.
After this operation, 53.2 kB of additional disk space will be used.

After this operation, 53.2 kB disk space will be freed.

**Comment by m-blaha** [comment]
And this is from zypper:

install:
Overall download size: 27.6 KiB. Already cached: 0 B. After the operation, additional 51.7 KiB will be used.

remove:
After the operation, 51.7 KiB will be freed.

**Comment by jrohel** [comment]
I made the above adjustments. And I replaced "incoming" with "inbound" as we have in the API.

The resulting output is:
```
Total size of inbound packages is 199 KiB. Need to download 199 KiB.
After unpacking 375 KiB will be used (install 473 KiB, remove 98 KiB).
```

The line `Total size of inbound...` is displayed only in the case of a non-zero value of inbound packages.

**Comment by m-blaha** [comment]
Although I understand your point about accurateness, I would still prefer `After this operation xx will be used/freed` wording. This way the line could remain the same for any transaction, regardless it's install or remove.
In the documentation we can describe in detail that these numbers cover only sum of packages sizes from metadata.

**Comment by jrohel** [comment]
@m-blaha OK. I rebased the PR and changed the message to `After this operation xxx will be used/freed (install xxx, remove xxx).`.

**Review by jan-kolarik — APPROVED** [review]
Great, thanks!

**Pull request merged**
