### PR TITLE
config: add search (se) and info (if) aliases

### PR DESCRIPTION
**Pull request by pennbauman**
Adds two command aliases present in dnf4:

- `se` for the `search` command
- `if` for the `info` command

### CODE REVIEW

**Comment by ppisar** [comment]
What's the reason for adding the aliases?

**Comment by ppisar** [comment]
> What's the reason for adding the aliases?

I see dnf4.

**Comment by j-mracek** [comment]
The question is whether compatibility aliases with zypper should be maintained in the upstream of DNF5. DNF5 introduce aliases defined in config files to allow customization on distribution sides.

**Comment by pennbauman** [comment]
These are aliases I personally use regularly, and I assume there are others who use them too. 

dnf5 already has several aliases in this style (eg `in` for `install`, `rm` for `remove`), so I would think it makes sense to include these too.

**Comment by Conan-Kudo** [comment]
I agree as well. I personally regularly use the aliases we introduced in dnf4 and I would prefer that they be retained by default in dnf5.

**Review by Conan-Kudo — APPROVED** [review]

**Pull request merged**
