### PR TITLE
Add packit job to run ABI check on testing farm

### PR DESCRIPTION
**Pull request by kontura**
Requires: https://github.com/rpm-software-management/ci-dnf-stack/pull/1595

### CODE REVIEW

**Comment by kontura** [comment]
For: https://github.com/rpm-software-management/dnf5/issues/1651

**Comment by kontura** [comment]
And actually after the crash fix is released it will fail on the lack of support of running `builddep` on remote files: https://github.com/rpm-software-management/dnf5/issues/1796

**Review by jan-kolarik — APPROVED** [review]
Thanks! Seems fine, I'll just wait for the test to be re-run.

**Pull request merged**
