### PR TITLE
advisory: document advisory command changes and few clean ups

### PR DESCRIPTION
**Pull request by kontura**
Closes: https://github.com/rpm-software-management/dnf5/issues/919

### CODE REVIEW

**Comment by pkratoch** [comment]
Hi, the PR doesn't address this part of the issue: "`dnf5 updateinfo --help` does not provide any options while several options are listed in the man page". Do you plan to add it? Otherwise, the issue shouldn't be marked as closed by this.

**Comment by pkratoch** [comment]
Also, I noticed that in the `changes.rst` document, single backticks are used everywhere to indicate command substitution, while for example in `dnf5.8.rst`, double backticks are used. When I build the documentation, the single backtics produce italics instead of literal, so if doesn't show e.g. options correctly. Is it the same for you or is there a special setting I am missing?

**Comment by kontura** [comment]
> Hi, the PR doesn't address this part of the issue: "`dnf5 updateinfo --help` does not provide any options while several options are listed in the man page". Do you plan to add it? Otherwise, the issue shouldn't be marked as closed by this.

That part was extracted into a separate issue: https://github.com/rpm-software-management/dnf5/issues/921 which was closed in the mean time.

 

> Also, I noticed that in the `changes.rst` document, single backticks are used everywhere to indicate command substitution, while for example in `dnf5.8.rst`, double backticks are used. When I build the documentation, the single backtics produce italics instead of literal, so if doesn't show e.g. options correctly. Is it the same for you or is there a special setting I am missing?

Yea, I am seeing the same. It is also here: https://dnf5.readthedocs.io/en/latest/changes.html. I added a commit to switch that to double backticks. What do you think?

**Comment by pkratoch** [comment]
> > Hi, the PR doesn't address this part of the issue: "`dnf5 updateinfo --help` does not provide any options while several options are listed in the man page". Do you plan to add it? Otherwise, the issue shouldn't be marked as closed by this.
> 
> That part was extracted into a separate issue: #921 which was closed in the mean time.

I see, ok.

> > Also, I noticed that in the `changes.rst` document, single backticks are used everywhere to indicate command substitution, while for example in `dnf5.8.rst`, double backticks are used. When I build the documentation, the single backtics produce italics instead of literal, so if doesn't show e.g. options correctly. Is it the same for you or is there a special setting I am missing?
> 
> Yea, I am seeing the same. It is also here: https://dnf5.readthedocs.io/en/latest/changes.html. I added a commit to switch that to double backticks. What do you think?

Looks good, thanks.

**Pull request merged**
