### PR TITLE
Support RPMTRANS_FLAG_DEPLOOPS

### PR DESCRIPTION
**Pull request by opoplawski**
I think this could be helpful for debugging some installer issues - e.g. https://bugzilla.redhat.com/show_bug.cgi?id=2244744

### CODE REVIEW

**Comment by ppisar** [comment]
Does it help anything? According to rpm sources, it only changes logging the loops from a debug level to a warning level.

**Review by pmatilai — APPROVED** [review]
It helps diagnostics on packaging dependency loops, which are getting ever more popular.

For everybody's sanity, this should've been added to yum twenty years ago, but I think Python 2 had issues with the (1 << 31) enum value.

**Comment by pmatilai** [comment]
To elaborate: currently when somebody reports a bug that is an obvious (to me anyway) dependency loop situation, it's often reported against anaconda where it then gets tossed to whatever random package is failing and then after a few false tries it ends up on rpm for comments.
At which point I get to figure out how to reproduce it with dnf, then do 'dnf --installroot=/test --downloadonly <whatever>', followed by 'rpm -Uv --test --deploops $(find /test/var/cache/dnf -name "*.rpm")' to get the loop analysis from rpm.

With this one-liner patch, all that becomes a dnf one-liner.

**Comment by ppisar** [comment]
I understand what it is good for. My question targets to DNF5: Does DNF5 display RPM warnings or is it rather librpm to print directly to stderr and mixing up, potentially in the middle of a word, with DNF5 output? Does DNF5 log RPM debug messages into DNF5 log? If it logs, then the user should find the strongly connected components debugging there already without this patch.

**Comment by j-mracek** [comment]
There is a simirar patch for DNF4. I've approve it.

**Comment by ppisar** [comment]
Orion, does your patch prints anything related to SCC? I cannot reproduce it with:

~~~~
~test/dnf5/redhat-linux-build/dnf5/dnf5 --use-host-config --setopt=tsflags=deploops --disablerepo=rawhide --enablerepo='fedora' --enablerepo='updates' --enablerepo=updates-testing --releasever=40 --installroot=/tmp/r install postfix
~~~~

Instead I get an error:

~~~~
>>> Stop pre-install scriptlet: ca-certificates-0:2023.2.62_v7.0.401-6.fc40.noarch
>>> Error in pre-install scriptlet: ca-certificates-0:2023.2.62_v7.0.401-6.fc40.noarch return code 2
>>> Running pre-install scriptlet: rpm-0:4.19.1.1-1.fc40.x86_64
>>> Stop pre-install scriptlet: rpm-0:4.19.1.1-1.fc40.x86_64
>>> Error in pre-install scriptlet: rpm-0:4.19.1.1-1.fc40.x86_64 return code 2
~~~~

But that error does not depend --setopt=tsflags=deploops.

Were Fedora 40 repositories fixed in between?

**Comment by pmatilai** [comment]
Oh, right, forgot about dnf eating up rpm's output. In that case dnf could just leave the flag always on, that'd be okay too.

**Comment by opoplawski** [comment]
Honestly, this is completely untested.  I figured though that is was at least the first step for trying to get the desired output.

**Comment by ppisar** [comment]
The log is also missing the rpm log:

~~~~
2024-02-27T16:02:06+0000 [21663] INFO RPM callback open file "/tmp/r/var/cache/libdnf5/fedora-6c3a9e5977a00788/packages/ca-certificates-2023.2.62_v7.0.401-6.fc40.noarch.rpm"
2024-02-27T16:02:07+0000 [21663] INFO RPM callback close file
2024-02-27T16:02:07+0000 [21663] ERROR [rpm] ca-certificates-2023.2.62_v7.0.401-6.fc40.noarch: install failed
2024-02-27T16:02:07+0000 [21663] INFO RPM callback open file "/tmp/r/var/cache/libdnf5/fedora-6c3a9e5977a00788/packages/rpm-4.19.1.1-1.fc40.x86_64.rpm"
2024-02-27T16:02:07+0000 [21663] INFO RPM callback close file
2024-02-27T16:02:07+0000 [21663] ERROR [rpm] rpm-4.19.1.1-1.fc40.x86_64: install failed
~~~~

**Comment by opoplawski** [comment]
> ```
> 2024-02-27T16:02:06+0000 [21663] INFO RPM callback open file "/tmp/r/var/cache/libdnf5/fedora-6c3a9e5977a00788/packages/ca-certificates-2023.2.62_v7.0.401-6.fc40.noarch.rpm"
> 2024-02-27T16:02:07+0000 [21663] INFO RPM callback close file
> 2024-02-27T16:02:07+0000 [21663] ERROR [rpm] ca-certificates-2023.2.62_v7.0.401-6.fc40.noarch: install failed
> 2024-02-27T16:02:07+0000 [21663] INFO RPM callback open file "/tmp/r/var/cache/libdnf5/fedora-6c3a9e5977a00788/packages/rpm-4.19.1.1-1.fc40.x86_64.rpm"
> 2024-02-27T16:02:07+0000 [21663] INFO RPM callback close file
> 2024-02-27T16:02:07+0000 [21663] ERROR [rpm] rpm-4.19.1.1-1.fc40.x86_64: install failed
> ```

This is exactly the error that this added option would hopefully help us debug.  We would hope to see rpm output like:
```
Running transaction test
warning: SCC #1: 133 members (28 external dependencies)
warning:        alternatives-1.26-3.fc40.x86_64
warning:                -> glibc-2.39-2.fc40.x86_64
warning:        postfix-2:3.8.5-3.fc40.x86_64
warning:                => systemd-255.3-1.fc40.x86_64
warning:                -> policycoreutils-3.6-3.fc40.x86_64
warning:                -> cyrus-sasl-lib-2.1.28-19.fc40.x86_64
...
warning:        bzip2-libs-1.0.8-18.fc40.x86_64
warning:                -> glibc-2.39-2.fc40.x86_64
Transaction test succeeded.
Running transaction
```
Unfortunately it appears that dnf5 has become FTBFS in rawhide.  I guess I'll try shifting to F40 itself.

**Comment by ppisar** [comment]
> Unfortunately it appears that dnf5 has become FTBFS in rawhide. I guess I'll try shifting to F40 itself.

F40 suffers from the same FTBFS triggered by swig 4.2.1. You need to apply upstream commit 2ee2bd982df78201c35efac896a7219a9639f7e6 if you work on Fedora sources.

**Comment by j-mracek** [comment]
I think that the patch is OK and can be merged to DNF5

**Pull request merged**
