### PR TITLE
repoquery: Do not treat packages with GROUP reason as userinstalled

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]

**Review by j-mracek — CHANGES_REQUESTED** [review]
I do not agree with the change because it will break autoremove functionality. The filter is used in unneeded filter. The change does not provide any description why the change is required and what king of issue it resolves.

**Comment by Conan-Kudo** [comment]
Hmm, that reasoning makes sense. To be clear, I thought `GROUP` basically was the equivalent of dep-installed for packages that users installed by requesting a group. If it's not that, then this change makes no sense.

**Comment by ignatenkobrain** [comment]
`dnf5 repoquery --userinstalled` shows packages from GROUPs.

**Comment by j-mracek** [comment]
The command that you are looking for is:
`sudo dnf5 repoquery --installed --qf '%{name}.%{arch} & %{reason}\n' | grep '& User'`
I am really sorry but the PR cannot be merged because it will break DNF5 behavior.

**Pull request closed without merging**
