### PR TITLE
Use correct path when destdir option is set

### PR DESCRIPTION
**Pull request by m-blaha**
Changes:

1e83b073 (Marek Blaha, 9 minutes ago)
   repo: New Repo.get_packages_download_dir() method

   Currently, the path where a package should be downloaded is computed in 
   several places. This patch introduces a single location for this 
   computation to reduce code duplication. The patch also fixes usage of
   incorrect package path in Package::get_package_path() call - the destdir
   config option was not taken into account.

07105d0b (Marek Blaha, 2 hours ago)
   doc: Document destdir main config option

Resolves: https://github.com/rpm-software-management/dnf5/issues/1620
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1536

### CODE REVIEW

**Comment by pkratoch** [comment]
Thanks for the patch! I noticed one test that looks related to the change broke ("skip downloading of already downloaded rpm file" in the dnf/download.feature).

**Comment by m-blaha** [comment]
Yeah, I was lazy to run the tests locally and that's the result... I'll check it out, meanwhile switching to draft state.

**Comment by m-blaha** [comment]
So the issue is not with this PR itself, but was introduced in commit 59538f3e which did not properly call download callbacks in case the source and destination of a downloaded file were the same. The problem did not surface before this PR, because the package was not correctly identified as locally available due to an incorrect path being used.

**Comment by pkratoch** [comment]
Thank you!

**Pull request merged**
