### PR TITLE
Package file documenting dnf4/dnf5 changes as man page

### PR DESCRIPTION
**Pull request by m-blaha**
Resolves: https://github.com/rpm-software-management/dnf5/issues/1674

### CODE REVIEW

**Comment by evan-goode** [comment]
I would rather the document be called `changes-from-dnf4`. What do you think?

**Comment by m-blaha** [comment]
> I would rather the document be called `changes-from-dnf4`. What do you think?

Yeah, that might be even clearer.

**Comment by m-blaha** [comment]
The document is renamed to `changes-from-dnf4`.

**Review by ppisar — APPROVED** [review]
Good.

**Pull request merged**
